// Generated by scripts/extract-sounds.mjs from beer_exe/BEER.DAT.
// Do not edit by hand; re-run the script.
// biome-ignore-all lint/suspicious/noApproximativeNumericConstant: generated durations
export interface SoundDef {
  key: string;
  file: string;
  seconds: number;
  source: string;
}

export interface LevelCues {
  explosion: string | null;
  bossExplosion: string | null;
  enemyShot: string | null;
  cue: string | null;
}

export const SOUNDS: SoundDef[] = [
  {
    key: "menu",
    file: "assets/sounds/menu.ogg",
    seconds: 4.014,
    source: "MENU.SND (single, pcm8)",
  },
  {
    key: "go",
    file: "assets/sounds/go.ogg",
    seconds: 7.963,
    source: "GO.SND (single, pcm8)",
  },
  {
    key: "close",
    file: "assets/sounds/close.ogg",
    seconds: 3.964,
    source: "CLOSE.SND (single, pcm8)",
  },
  {
    key: "sell",
    file: "assets/sounds/sell.ogg",
    seconds: 3.515,
    source: "SELL.SND (single, pcm8)",
  },
  {
    key: "buy",
    file: "assets/sounds/buy.ogg",
    seconds: 15.666,
    source: "BUY.SND (single, pcm8)",
  },
  {
    key: "tod",
    file: "assets/sounds/tod.ogg",
    seconds: 7.077,
    source: "TOD.SND (single, pcm8)",
  },
  {
    key: "blick",
    file: "assets/sounds/blick.ogg",
    seconds: 15.622,
    source: "BLICK.SND (single, pcm8)",
  },
  {
    key: "longtime",
    file: "assets/sounds/longtime.ogg",
    seconds: 18.098,
    source: "LONGTIME.SND (single, pcm8)",
  },
  {
    key: "level1-snd0",
    file: "assets/sounds/level1-snd0.ogg",
    seconds: 0.462,
    source: "LEVEL0.SND#0 (pcm8)",
  },
  {
    key: "level1-snd1",
    file: "assets/sounds/level1-snd1.ogg",
    seconds: 14.595,
    source: "LEVEL0.SND#1 (adpcm4)",
  },
  {
    key: "level2-snd0",
    file: "assets/sounds/level2-snd0.ogg",
    seconds: 0.8,
    source: "LEVEL1.SND#0 (adpcm4)",
  },
  {
    key: "level2-snd1",
    file: "assets/sounds/level2-snd1.ogg",
    seconds: 0.855,
    source: "LEVEL1.SND#1 (adpcm4)",
  },
  {
    key: "level2-snd2",
    file: "assets/sounds/level2-snd2.ogg",
    seconds: 0.48,
    source: "LEVEL1.SND#2 (adpcm4)",
  },
  {
    key: "level2-snd3",
    file: "assets/sounds/level2-snd3.ogg",
    seconds: 1.415,
    source: "LEVEL1.SND#3 (adpcm4)",
  },
  {
    key: "level2-snd4",
    file: "assets/sounds/level2-snd4.ogg",
    seconds: 1.932,
    source: "LEVEL1.SND#4 (adpcm4)",
  },
  {
    key: "level2-snd5",
    file: "assets/sounds/level2-snd5.ogg",
    seconds: 3.374,
    source: "LEVEL1.SND#5 (adpcm4)",
  },
  {
    key: "level2-snd6",
    file: "assets/sounds/level2-snd6.ogg",
    seconds: 0.826,
    source: "LEVEL1.SND#6 (adpcm4)",
  },
  {
    key: "level2-snd7",
    file: "assets/sounds/level2-snd7.ogg",
    seconds: 0.564,
    source: "LEVEL1.SND#7 (adpcm4)",
  },
  {
    key: "level2-snd8",
    file: "assets/sounds/level2-snd8.ogg",
    seconds: 1.633,
    source: "LEVEL1.SND#8 (adpcm4)",
  },
  {
    key: "level2-snd9",
    file: "assets/sounds/level2-snd9.ogg",
    seconds: 1.867,
    source: "LEVEL1.SND#9 (adpcm4)",
  },
  {
    key: "level2-snd10",
    file: "assets/sounds/level2-snd10.ogg",
    seconds: 0.392,
    source: "LEVEL1.SND#10 (adpcm4)",
  },
  {
    key: "level2-snd11",
    file: "assets/sounds/level2-snd11.ogg",
    seconds: 3.179,
    source: "LEVEL1.SND#11 (adpcm4)",
  },
  {
    key: "level2-snd12",
    file: "assets/sounds/level2-snd12.ogg",
    seconds: 0.462,
    source: "LEVEL1.SND#12 (pcm8)",
  },
  {
    key: "level2-snd13",
    file: "assets/sounds/level2-snd13.ogg",
    seconds: 0.528,
    source: "LEVEL1.SND#13 (pcm8)",
  },
  {
    key: "level2-snd14",
    file: "assets/sounds/level2-snd14.ogg",
    seconds: 1.627,
    source: "LEVEL1.SND#14 (pcm8)",
  },
  {
    key: "level2-snd15",
    file: "assets/sounds/level2-snd15.ogg",
    seconds: 1.436,
    source: "LEVEL1.SND#15 (pcm8)",
  },
  {
    key: "level2-snd16",
    file: "assets/sounds/level2-snd16.ogg",
    seconds: 0.154,
    source: "LEVEL1.SND#16 (adpcm4)",
  },
  {
    key: "level2-snd17",
    file: "assets/sounds/level2-snd17.ogg",
    seconds: 4.403,
    source: "LEVEL1.SND#17 (adpcm4)",
  },
  {
    key: "level2-snd18",
    file: "assets/sounds/level2-snd18.ogg",
    seconds: 4.361,
    source: "LEVEL1.SND#18 (adpcm4)",
  },
  {
    key: "level2-snd19",
    file: "assets/sounds/level2-snd19.ogg",
    seconds: 0.723,
    source: "LEVEL1.SND#19 (adpcm4)",
  },
  {
    key: "level2-snd20",
    file: "assets/sounds/level2-snd20.ogg",
    seconds: 1.781,
    source: "LEVEL1.SND#20 (adpcm4)",
  },
  {
    key: "level2-snd21",
    file: "assets/sounds/level2-snd21.ogg",
    seconds: 1.254,
    source: "LEVEL1.SND#21 (adpcm4)",
  },
  {
    key: "level2-snd22",
    file: "assets/sounds/level2-snd22.ogg",
    seconds: 2.174,
    source: "LEVEL1.SND#22 (adpcm4)",
  },
  {
    key: "level3-snd0",
    file: "assets/sounds/level3-snd0.ogg",
    seconds: 0.48,
    source: "LEVEL2.SND#0 (adpcm4)",
  },
  {
    key: "level3-snd1",
    file: "assets/sounds/level3-snd1.ogg",
    seconds: 1.415,
    source: "LEVEL2.SND#1 (adpcm4)",
  },
  {
    key: "level3-snd2",
    file: "assets/sounds/level3-snd2.ogg",
    seconds: 1.284,
    source: "LEVEL2.SND#2 (adpcm4)",
  },
  {
    key: "level3-snd3",
    file: "assets/sounds/level3-snd3.ogg",
    seconds: 0.826,
    source: "LEVEL2.SND#3 (adpcm4)",
  },
  {
    key: "level3-snd4",
    file: "assets/sounds/level3-snd4.ogg",
    seconds: 0.845,
    source: "LEVEL2.SND#4 (adpcm4)",
  },
  {
    key: "level3-snd5",
    file: "assets/sounds/level3-snd5.ogg",
    seconds: 1.688,
    source: "LEVEL2.SND#5 (adpcm4)",
  },
  {
    key: "level3-snd6",
    file: "assets/sounds/level3-snd6.ogg",
    seconds: 1.627,
    source: "LEVEL2.SND#6 (pcm8)",
  },
  {
    key: "level3-snd7",
    file: "assets/sounds/level3-snd7.ogg",
    seconds: 0.743,
    source: "LEVEL2.SND#7 (adpcm4)",
  },
  {
    key: "level3-snd8",
    file: "assets/sounds/level3-snd8.ogg",
    seconds: 7.987,
    source: "LEVEL2.SND#8 (adpcm4)",
  },
  {
    key: "level3-snd9",
    file: "assets/sounds/level3-snd9.ogg",
    seconds: 6.097,
    source: "LEVEL2.SND#9 (adpcm4)",
  },
  {
    key: "level3-snd10",
    file: "assets/sounds/level3-snd10.ogg",
    seconds: 0.266,
    source: "LEVEL2.SND#10 (adpcm4)",
  },
  {
    key: "level3-snd11",
    file: "assets/sounds/level3-snd11.ogg",
    seconds: 2.851,
    source: "LEVEL2.SND#11 (adpcm4)",
  },
  {
    key: "level3-snd12",
    file: "assets/sounds/level3-snd12.ogg",
    seconds: 0.154,
    source: "LEVEL2.SND#12 (adpcm4)",
  },
  {
    key: "level3-snd13",
    file: "assets/sounds/level3-snd13.ogg",
    seconds: 3.557,
    source: "LEVEL2.SND#13 (adpcm4)",
  },
  {
    key: "level3-snd14",
    file: "assets/sounds/level3-snd14.ogg",
    seconds: 0.691,
    source: "LEVEL2.SND#14 (adpcm4)",
  },
  {
    key: "level3-snd15",
    file: "assets/sounds/level3-snd15.ogg",
    seconds: 0.392,
    source: "LEVEL2.SND#15 (adpcm4)",
  },
  {
    key: "level3-snd16",
    file: "assets/sounds/level3-snd16.ogg",
    seconds: 2.174,
    source: "LEVEL2.SND#16 (adpcm4)",
  },
  {
    key: "level3-snd17",
    file: "assets/sounds/level3-snd17.ogg",
    seconds: 0.582,
    source: "LEVEL2.SND#17 (adpcm4)",
  },
  {
    key: "level3-snd18",
    file: "assets/sounds/level3-snd18.ogg",
    seconds: 0.972,
    source: "LEVEL2.SND#18 (pcm8)",
  },
  {
    key: "level3-snd19",
    file: "assets/sounds/level3-snd19.ogg",
    seconds: 0.304,
    source: "LEVEL2.SND#19 (pcm8)",
  },
  {
    key: "level3-snd20",
    file: "assets/sounds/level3-snd20.ogg",
    seconds: 3.688,
    source: "LEVEL2.SND#20 (adpcm4)",
  },
  {
    key: "level3-snd21",
    file: "assets/sounds/level3-snd21.ogg",
    seconds: 0.855,
    source: "LEVEL2.SND#21 (adpcm4)",
  },
  {
    key: "level3-snd22",
    file: "assets/sounds/level3-snd22.ogg",
    seconds: 1.781,
    source: "LEVEL2.SND#22 (adpcm4)",
  },
  {
    key: "level3-snd23",
    file: "assets/sounds/level3-snd23.ogg",
    seconds: 4.006,
    source: "LEVEL2.SND#23 (adpcm4)",
  },
  {
    key: "level4-snd0",
    file: "assets/sounds/level4-snd0.ogg",
    seconds: 0.925,
    source: "LEVEL3.SND#0 (adpcm4)",
  },
  {
    key: "level4-snd1",
    file: "assets/sounds/level4-snd1.ogg",
    seconds: 1.415,
    source: "LEVEL3.SND#1 (adpcm4)",
  },
  {
    key: "level4-snd2",
    file: "assets/sounds/level4-snd2.ogg",
    seconds: 2.046,
    source: "LEVEL3.SND#2 (adpcm4)",
  },
  {
    key: "level4-snd3",
    file: "assets/sounds/level4-snd3.ogg",
    seconds: 2.553,
    source: "LEVEL3.SND#3 (adpcm4)",
  },
  {
    key: "level4-snd4",
    file: "assets/sounds/level4-snd4.ogg",
    seconds: 0.678,
    source: "LEVEL3.SND#4 (adpcm4)",
  },
  {
    key: "level4-snd5",
    file: "assets/sounds/level4-snd5.ogg",
    seconds: 2.272,
    source: "LEVEL3.SND#5 (adpcm4)",
  },
  {
    key: "level4-snd6",
    file: "assets/sounds/level4-snd6.ogg",
    seconds: 2.919,
    source: "LEVEL3.SND#6 (adpcm4)",
  },
  {
    key: "level4-snd7",
    file: "assets/sounds/level4-snd7.ogg",
    seconds: 0.826,
    source: "LEVEL3.SND#7 (adpcm4)",
  },
  {
    key: "level4-snd8",
    file: "assets/sounds/level4-snd8.ogg",
    seconds: 6.257,
    source: "LEVEL3.SND#8 (adpcm4)",
  },
  {
    key: "level4-snd9",
    file: "assets/sounds/level4-snd9.ogg",
    seconds: 0.711,
    source: "LEVEL3.SND#9 (pcm8)",
  },
  {
    key: "level4-snd10",
    file: "assets/sounds/level4-snd10.ogg",
    seconds: 1.627,
    source: "LEVEL3.SND#10 (pcm8)",
  },
  {
    key: "level4-snd11",
    file: "assets/sounds/level4-snd11.ogg",
    seconds: 0.146,
    source: "LEVEL3.SND#11 (pcm8)",
  },
  {
    key: "level5-snd0",
    file: "assets/sounds/level5-snd0.ogg",
    seconds: 0.48,
    source: "LEVEL4.SND#0 (adpcm4)",
  },
  {
    key: "level5-snd1",
    file: "assets/sounds/level5-snd1.ogg",
    seconds: 1.442,
    source: "LEVEL4.SND#1 (adpcm4)",
  },
  {
    key: "level5-snd2",
    file: "assets/sounds/level5-snd2.ogg",
    seconds: 0.826,
    source: "LEVEL4.SND#2 (adpcm4)",
  },
  {
    key: "level5-snd3",
    file: "assets/sounds/level5-snd3.ogg",
    seconds: 2.477,
    source: "LEVEL4.SND#3 (adpcm4)",
  },
  {
    key: "level5-snd4",
    file: "assets/sounds/level5-snd4.ogg",
    seconds: 10.308,
    source: "LEVEL4.SND#4 (adpcm4)",
  },
  {
    key: "level5-snd5",
    file: "assets/sounds/level5-snd5.ogg",
    seconds: 2.735,
    source: "LEVEL4.SND#5 (adpcm4)",
  },
  {
    key: "level5-snd6",
    file: "assets/sounds/level5-snd6.ogg",
    seconds: 0.669,
    source: "LEVEL4.SND#6 (adpcm4)",
  },
  {
    key: "level5-snd7",
    file: "assets/sounds/level5-snd7.ogg",
    seconds: 1.627,
    source: "LEVEL4.SND#7 (pcm8)",
  },
  {
    key: "level5-snd8",
    file: "assets/sounds/level5-snd8.ogg",
    seconds: 1.172,
    source: "LEVEL4.SND#8 (pcm8)",
  },
  {
    key: "level5-snd9",
    file: "assets/sounds/level5-snd9.ogg",
    seconds: 1.255,
    source: "LEVEL4.SND#9 (adpcm4)",
  },
  {
    key: "level5-snd10",
    file: "assets/sounds/level5-snd10.ogg",
    seconds: 1.35,
    source: "LEVEL4.SND#10 (adpcm4)",
  },
  {
    key: "level5-snd11",
    file: "assets/sounds/level5-snd11.ogg",
    seconds: 0.462,
    source: "LEVEL4.SND#11 (pcm8)",
  },
  {
    key: "level5-snd12",
    file: "assets/sounds/level5-snd12.ogg",
    seconds: 1.651,
    source: "LEVEL4.SND#12 (adpcm4)",
  },
  {
    key: "level5-snd13",
    file: "assets/sounds/level5-snd13.ogg",
    seconds: 0.154,
    source: "LEVEL4.SND#13 (adpcm4)",
  },
  {
    key: "level5-snd14",
    file: "assets/sounds/level5-snd14.ogg",
    seconds: 2.553,
    source: "LEVEL4.SND#14 (adpcm4)",
  },
];

export const LEVEL_CUES: Record<number, LevelCues> = {
  1: {
    explosion: "level1-snd0",
    bossExplosion: "level1-snd0",
    enemyShot: null,
    cue: "level1-snd1",
  },
  2: {
    explosion: "level2-snd14",
    bossExplosion: "level2-snd17",
    enemyShot: "level2-snd16",
    cue: "level2-snd4",
  },
  3: {
    explosion: "level3-snd6",
    bossExplosion: "level3-snd9",
    enemyShot: "level3-snd12",
    cue: "level3-snd13",
  },
  4: {
    explosion: "level4-snd10",
    bossExplosion: "level4-snd6",
    enemyShot: "level4-snd11",
    cue: "level4-snd8",
  },
  5: {
    explosion: "level5-snd2",
    bossExplosion: "level5-snd3",
    enemyShot: "level5-snd13",
    cue: "level5-snd9",
  },
};
